# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('webhook', 'Webhook')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('template_key', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'db_table': 'dunning_notificationlog',
            },
        ),
        migrations.CreateModel(
            name='DunningPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('retry_offsets_days', models.JSONField(blank=True, default=list)),
                ('grace_period_days', models.PositiveIntegerField(default=0)),
                ('final_action', models.CharField(choices=[('cancel', 'Cancel Subscription'), ('pause', 'Pause Subscription'), ('mark_uncollectible', 'Mark Invoice Uncollectible'), ('do_nothing', 'Do Nothing')], default='cancel', max_length=24)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('notify_webhook', models.BooleanField(default=True)),
                ('hard_failure_behavior', models.CharField(choices=[('stop_until_pm_replaced', 'Stop until payment method replaced'), ('retry', 'Retry on schedule')], default='stop_until_pm_replaced', max_length=32)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'dunning_policy',
            },
        ),
        migrations.CreateModel(
            name='DunningRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended (awaiting payment method)'), ('recovered', 'Recovered'), ('exhausted', 'Exhausted'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('exhausted_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
            ],
            options={
                'db_table': 'dunning_run',
            },
        ),
    ]
