# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dunning', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dunningrun',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dunning_runs', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='dunning_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dunning.dunningrun'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant'),
        ),
        migrations.AddConstraint(
            model_name='dunningpolicy',
            constraint=models.UniqueConstraint(fields=('merchant', 'environment', 'name'), name='uniq_dunningpolicy_merchant_env_name'),
        ),
        migrations.AddIndex(
            model_name='dunningrun',
            index=models.Index(fields=['merchant', 'environment', 'status', 'next_retry_at'], name='dr_scope_status_retry_idx'),
        ),
        migrations.AddConstraint(
            model_name='dunningrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('invoice',), name='uniq_active_dunningrun_per_invoice'),
        ),
    ]
