services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-subpilot}
      POSTGRES_USER: ${POSTGRES_USER:-subpilot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-subpilot}
    volumes:
      - subpilot_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-subpilot} -d ${POSTGRES_DB:-subpilot}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  migrate:
    build: .
    command: python manage.py migrate --noinput
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started

  worker:
    build: .
    command: celery -A config worker -Q billing,payments,dunning,webhooks,notifications,analytics -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

volumes:
  subpilot_db_data:
