# Generated by Django 5.0.10 on 2026-06-20 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merchant_metadata'),
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='accounts.merchant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_admin.platformadmin')),
            ],
            options={
                'db_table': 'platform_admin_merchantconfig',
            },
        ),
    ]
