# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('secret_encrypted', models.CharField(blank=True, default='', max_length=512)),
                ('event_filters', models.JSONField(blank=True, default=list)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'events_webhookendpoint',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(blank=True, default='', max_length=64)),
                ('aggregate_id', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'events_webhookevent',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_status_code', models.IntegerField(blank=True, null=True)),
                ('last_response_body', models.TextField(blank=True, default='')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.webhookendpoint')),
                ('webhook_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='events.webhookevent')),
            ],
            options={
                'db_table': 'events_webhookdelivery',
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['merchant', 'environment', 'enabled'], name='wh_endpoint_scope_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['merchant', 'environment', 'event_type', 'occurred_at'], name='webhookevent_scope_type_at_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='delivery_status_nextat_idx'),
        ),
    ]
