# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('dunning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dunning_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='dunning.dunningpolicy'),
        ),
        migrations.AddField(
            model_name='plan',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment'),
        ),
        migrations.AddField(
            model_name='plan',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.plan'),
        ),
        migrations.AddField(
            model_name='priceversion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_versions', to='catalog.plan'),
        ),
        migrations.AddField(
            model_name='product',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant'),
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='planfeature',
            constraint=models.UniqueConstraint(fields=('plan', 'label'), name='uniq_planfeature_plan_label'),
        ),
        migrations.AddIndex(
            model_name='priceversion',
            index=models.Index(fields=['plan', 'active_from'], name='priceversion_plan_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceversion',
            constraint=models.CheckConstraint(check=models.Q(('amount_minor__gt', 0)), name='priceversion_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='priceversion',
            constraint=models.CheckConstraint(check=models.Q(('interval_count__gt', 0)), name='priceversion_interval_positive'),
        ),
        migrations.AddConstraint(
            model_name='priceversion',
            constraint=models.UniqueConstraint(condition=models.Q(('active_to__isnull', True)), fields=('plan',), name='uniq_active_priceversion_per_plan'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['merchant', 'environment', 'status'], name='product_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('merchant', 'environment', 'name'), name='uniq_product_merchant_env_name'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['merchant', 'environment', 'status'], name='plan_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('merchant', 'environment', 'product', 'name'), name='uniq_plan_merchant_env_product_name'),
        ),
    ]
