# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'customers_customer',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('nomba', 'Nomba'), ('mock', 'Mock (demo)')], default='nomba', max_length=16)),
                ('token_encrypted', models.CharField(blank=True, default='', max_length=512)),
                ('brand', models.CharField(blank=True, default='', max_length=32)),
                ('last4', models.CharField(blank=True, default='', max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='customers.customer')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'customers_paymentmethod',
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('return_url', models.URLField(blank=True, default='', max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='customers.customer')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
            ],
            options={
                'db_table': 'customers_portalsession',
            },
        ),
    ]
