# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsession',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_sessions', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['merchant', 'environment', 'email'], name='customer_scope_email_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['merchant', 'environment', 'status'], name='customer_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('merchant', 'environment', 'external_id'), name='uniq_customer_external_id_per_env'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['merchant', 'environment', 'customer', 'status'], name='pm_scope_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'active')), fields=('customer',), name='uniq_default_active_pm_per_customer'),
        ),
        migrations.AddIndex(
            model_name='portalsession',
            index=models.Index(fields=['merchant', 'environment', 'customer'], name='ps_scope_customer_idx'),
        ),
    ]
