# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('one_time', 'One Time'), ('setup_fee', 'Setup Fee'), ('proration', 'Proration'), ('discount', 'Discount'), ('tax', 'Tax'), ('credit', 'Credit')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('amount_minor', models.BigIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'invoices_lineitem',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.CharField(choices=[('refund', 'Refund'), ('duplicate', 'Duplicate Charge'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'invoices_creditnote',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], db_index=True, default='draft', max_length=16)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('discount_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('amount_due_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('hosted_payment_url', models.URLField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'invoices_invoice',
            },
        ),
    ]
