# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="hosted_payment_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
