# Generated by Django 5.0.10 on 2026-06-19 22:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0002_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('nomba', 'Nomba'), ('mock', 'Mock')], default='nomba', max_length=16)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('processor_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
            ],
            options={
                'db_table': 'payments_processorevent',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=400)),
                ('processor_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.environment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='invoices.invoice')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.merchant')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempts', to='customers.paymentmethod')),
            ],
            options={
                'db_table': 'payments_paymentattempt',
                'indexes': [models.Index(fields=['merchant', 'environment', 'status', 'next_retry_at'], name='pa_scope_status_retry_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('invoice', 'attempt_number'), name='uniq_paymentattempt_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('merchant', 'environment', 'idempotency_key'), name='uniq_paymentattempt_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='processorevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='uniq_processorevent_provider_id'),
        ),
    ]
