# Generated by Codex on 2026-06-20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
        ("payments", "0002_paymentattempt_metadata"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processorevent",
            name="uniq_processorevent_provider_id",
        ),
        migrations.CreateModel(
            name="BalanceTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("refund", "Refund"),
                            ("credit", "Credit"),
                            ("adjustment", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("signed_amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "processor_reference",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balance_transactions",
                        to="invoices.creditnote",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.environment",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_transactions",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.merchant",
                    ),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balance_transactions",
                        to="payments.paymentattempt",
                    ),
                ),
            ],
            options={
                "db_table": "payments_balancetransaction",
            },
        ),
        migrations.AddConstraint(
            model_name="processorevent",
            constraint=models.UniqueConstraint(
                fields=("merchant", "environment", "provider", "provider_event_id"),
                name="uniq_processorevent_scope_provider_id",
            ),
        ),
        migrations.AddIndex(
            model_name="balancetransaction",
            index=models.Index(
                fields=["merchant", "environment", "created_at"],
                name="bt_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="balancetransaction",
            index=models.Index(
                fields=["merchant", "environment", "type", "created_at"],
                name="bt_scope_type_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="balancetransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("signed_amount_minor", 0), _negated=True),
                name="bt_signed_amount_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="balancetransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("merchant", "environment", "idempotency_key"),
                name="uniq_bt_scope_idempotency",
            ),
        ),
    ]
