# Generated by Codex on 2026-07-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_environment_nomba_oauth_state"),
        ("payments", "0003_balance_transactions_and_scoped_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessorWebhookReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("nomba", "Nomba"), ("mock", "Mock")],
                        max_length=16,
                    ),
                ),
                ("mode", models.CharField(blank=True, default="", max_length=32)),
                (
                    "provider_event_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "processor_reference",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("outcome", models.CharField(db_index=True, max_length=32)),
                (
                    "failure_reason",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("response_status_code", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("method", models.CharField(blank=True, default="", max_length=12)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.environment",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "payments_processorwebhookreceipt",
            },
        ),
        migrations.AddIndex(
            model_name="processorwebhookreceipt",
            index=models.Index(
                fields=["provider", "outcome", "-received_at"],
                name="pwr_provider_outcome_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processorwebhookreceipt",
            index=models.Index(
                fields=["merchant", "environment", "-received_at"],
                name="pwr_scope_received_idx",
            ),
        ),
    ]
